changelog:
  exclude:
    authors:
      - allcontributors[bot]
      - dependabot[bot]
  categories:
    - title: 💥 Breaking Changes 💥
      labels:
        - breaking change
    - title: ✨ New Features ✨
      labels:
        - feature
    - title: 🔒 Security 🔒
      labels:
        - security
    - title: 🐛 Bug Fixes 🐛
      labels:
        - bug
    - title: 🧑 Accessibility 🧑
      labels:
        - accessibility
    - title: ⛑️ Trust & Safety ⛑️
      labels:
        - trust+safety
    - title: 🔋 Sustainability & Performance 🔋
      labels:
        - sustainability
        - performance
    - title: 🌍 Internationalization 🌏
      labels:
        - localisation
    - title: 🛠️ Other Improvements 🛠️
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
