name: Translation Sync

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sync:
    if: github.triggering_actor != 'allcontributors[bot]'
    strategy:
      matrix:
        locale:
          - cs
          - de
          - es
          - fr
          - ja
          - nl
          - pl
          - pt
          - ru
          - zh-CN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Sync to translation.io
        run: bundle exec rake translation:sync_and_show_purgeable
        env:
          TRANSLATION_IO_API_KEY: "${{ secrets.TRANSLATION_IO_API_KEY }}"
      - name: Organize changes
        run: "bundle exec i18n-tasks normalize -p -l en,${{ matrix.locale }}"
      - name: Open pull request with changes
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.TRANSLATION_SYNC_PAT }}"
          commit-message: "Automatically synced translations: ${{ matrix.locale }}"
          branch: "i18n/sync-${{ matrix.locale }}"
          labels: improvement,localisation
          title: "Translations updated: ${{ matrix.locale }}"
          delete-branch: true
          add-paths: config/locales
